name: flutter_erp_ui
description: A simple ERP front UI for Windows made with Flutter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.13.0
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
